/**
 * 配置加载
 */
import 'dotenv/config'
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs'
import { dirname, join } from 'path'
import { homedir } from 'os'
import { logger } from './logger.js'

export interface AppConfig {
  port: number
  dsh: {
    baseUrl: string
    preset: string
    /** dsh headless 执行层用的 provider(如 minimax-cn / tokenhub) */
    executorProvider: string
    /** provider 下的 model id */
    executorModel: string
    /** provider 的 API key(注入子进程环境变量,settings.yaml 的 apiKeyEnv 读取) */
    executorApiKey: string
    /** apiKeyEnv 名称(settings.yaml 里 provider 声明的环境变量名) */
    executorApiKeyEnv: string
  }
  funasr: {
    url: string
  }
  projectScanDirs: string[]
  llm: {
    apiKey: string
    model: string
    baseUrl: string
  }
  log: {
    level: string
  }
}

export function loadConfig(): AppConfig {
  return {
    port: Number(process.env.PORT) || 4001,
    dsh: {
      baseUrl: process.env.DSH_BASE_URL || 'http://127.0.0.1:3080',
      preset: process.env.DSH_PRESET || 'ai-meeting-assistant',
      executorProvider: process.env.DSH_EXECUTOR_PROVIDER || 'minimax-cn',
      executorModel: process.env.DSH_EXECUTOR_MODEL || 'MiniMax-M3',
      executorApiKey: process.env.DSH_EXECUTOR_API_KEY || process.env.MINIMAX_CN_API_KEY || '',
      executorApiKeyEnv: process.env.DSH_EXECUTOR_API_KEY_ENV || 'MINIMAX_CN_API_KEY',
    },
    funasr: {
      url: process.env.FUNASR_URL || 'ws://localhost:10095',
    },
    projectScanDirs: JSON.parse(process.env.PROJECT_SCAN_DIRS || '["D:\\\\projects","D:\\\\workspace"]'),
    llm: {
      apiKey: process.env.MINIMAX_CN_API_KEY || process.env.ANTHROPIC_API_KEY || '',
      model: process.env.LLM_MODEL || 'MiniMax-M3',
      baseUrl: process.env.LLM_BASE_URL || 'https://api.minimaxi.com/anthropic',
    },
    log: {
      level: process.env.LOG_LEVEL || 'info',
    },
  }
}

/**
 * 把 .env 里的执行层模型配置写入 dsh headless profile 的 patch 文件。
 *
 * dsh 的 agent-default-model 走 settings 体系(无环境变量入口),
 * 官方隔离方式是 profile 层的 cordis.patch.yml。
 * 我们在 server 启动时幂等覆盖这个文件 → .env 成为唯一配置源。
 */
export function syncDshExecutorConfig(config: AppConfig): void {
  const patchPath = join(homedir(), '.dsh', 'profiles', 'headless', 'cordis.patch.yml')

  const patchContent = [
    '# AUTO-GENERATED by meeting-assistant-server (from .env) — do not edit manually',
    '- id: agent-default-model',
    '  config:',
    `    provider: ${config.dsh.executorProvider}`,
    `    model: ${config.dsh.executorModel}`,
    '',
  ].join('\n')

  try {
    // 幂等:内容没变就不写(避免触发 dsh 热重载)
    if (existsSync(patchPath)) {
      const existing = readFileSync(patchPath, 'utf-8')
      if (existing.trim() === patchContent.trim()) {
        logger.info({ patchPath, provider: config.dsh.executorProvider, model: config.dsh.executorModel }, 'dsh executor config already up to date')
        return
      }
    }
    mkdirSync(dirname(patchPath), { recursive: true })
    writeFileSync(patchPath, patchContent, 'utf-8')
    logger.info({
      patchPath,
      provider: config.dsh.executorProvider,
      model: config.dsh.executorModel,
      apiKeyEnv: config.dsh.executorApiKeyEnv,
    }, 'dsh executor config synced to profile patch')
  } catch (err) {
    logger.warn({ err, patchPath }, 'failed to sync dsh executor config (dsh will use its current default)')
  }
}
